package control;
import java.security.SecureRandom;
import java.util.Random;

import static control.EVRP.printSolution;
import static control.Heuristic.runHeuristic;

public class Main {
    public static int TERMINATION;

    /****************************************************************/
    public static void main(String[] args) throws Exception {
        // read the file name from the args
        if (args.length<2) {
            System.err.println("Args are not supplied : ");
            System.exit(2);
        }
        String param = args[0];
        if(param.equals("-f")){
            EVRP.problemInstance = args[1];
        }

        /*Step 1*/
        EVRP.readProblem();   //Read EVRP from file from EVRP.h
        TERMINATION = 25000 * EVRP.INSTANCE.getActuelProblemSize();

        /*Step 2*/
        Stats.openStats();//open text files to store the best values from the 20 runs stats.h

        for (int run = 1; run <= EVRP.MAX_TRIALS; run++) {
            /*Step 3*/

            startRun(run);
            //Initialize your heuristic here
            Heuristic.initializeHeuristic();


            /*Step 4*/
            //Execute your heuristic
            while (!terminationCondition()) {
                runHeuristic();
            }
            printSolution(EVRP.bestSol.getTour(),EVRP.bestSol.getSteps());
      /*Note that the solution generated by the random heuristic may not
      be feasisble in terms of energy when checkSolution is utilized.
      The implementation is only for your reference*/
            /*Step 5*/
            endRun(run);  //store the best solution quality for each run

        }
        /*Step 6*/
        Stats.closeStats(); //close text files to calculate the mean result from the 20 runs
    }

    /*initialiazes a run for your heuristic*/
    static void startRun(int r) {
        Random rand = new Random();
        rand.setSeed(r);
       EVRP.currentBest = Double.MAX_VALUE;
       EVRP.evals=0;

        // Random rand = new SecureRandom(); r=rand.nextInt(r);
        System.out.println("Run: " + r + " with random seed " + r);
    }

    /*gets an observation of the run for your heuristic*/
    static void endRun(int r) {
        Stats.getMean(r - 1,EVRP.currentBest); //from stats.h
        System.out.println("End of run " + r + " with best solution quality "
                + EVRP.currentBest + " total evaluations: " + EVRP.evals);
    }

    /*sets the termination conidition for your heuristic*/
    static boolean terminationCondition() {

        return EVRP.evals >= TERMINATION;

    }

}